In [ ]:
import requests
import pandas as pd
import sqlite3

In [ ]:
from google.colab import userdata
import requests

API_KEY = userdata.get('TMDB_API_KEY')

url = "https://api.themoviedb.org/3/discover/movie"

params = {
    "api_key": API_KEY
}

response = requests.get(url, params=params)
data = response.json()

In [ ]:
movies = data['results']

df = pd.DataFrame(movies)

# Select useful columns (optional but cleaner)
df = df[[
    'id', 'title', 'release_date', 'popularity',
    'vote_average', 'vote_count', 'genre_ids'
]]

df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,718.2018,6.000,10,"[10749, 18]"
1,875828,Peaky Blinders: The Immortal Man,2026-03-05,290.8743,7.363,476,"[80, 18]"
2,83533,Avatar: Fire and Ash,2025-12-17,304.5720,7.260,1946,"[878, 12, 14]"
3,687163,Project Hail Mary,2026-03-15,298.5383,8.183,587,"[878, 12]"
4,1290821,Shelter,2026-01-28,291.7651,6.733,410,"[28, 80, 53]"

In [ ]:
df['genre_ids'] = df['genre_ids'].apply(lambda x: str(x))

In [ ]:
conn = sqlite3.connect("movies.db")

df.to_sql("movies", conn, if_exists="replace", index=False)

conn.close()

In [ ]:
conn = sqlite3.connect("movies.db")

movies_df = pd.read_sql("SELECT * FROM movies", conn)

conn.close()

In [ ]:
import ast
movies_df['genre_ids'] = movies_df['genre_ids'].apply(ast.literal_eval)

In [ ]:
movies_df.head()

,id,title,release_date,popularity,vote_average,vote_count,genre_ids
0,1523145,Your Heart Will Be Broken,2026-03-26,718.2018,6.000,10,"[10749, 18]"
1,875828,Peaky Blinders: The Immortal Man,2026-03-05,290.8743,7.363,476,"[80, 18]"
2,83533,Avatar: Fire and Ash,2025-12-17,304.5720,7.260,1946,"[878, 12, 14]"
3,687163,Project Hail Mary,2026-03-15,298.5383,8.183,587,"[878, 12]"
4,1290821,Shelter,2026-01-28,291.7651,6.733,410,"[28, 80, 53]"

In [ ]:
movies_df.describe()

                 id  popularity  vote_average   vote_count
count  2.000000e+01   20.000000     20.000000    20.000000
mean   1.135781e+06  227.072810      6.974200   564.450000
std    3.272576e+05  136.226495      0.676037   631.317626
min    8.353300e+04  105.917100      5.800000    10.000000
25%    1.084228e+06  125.465700      6.400000   151.750000
50%    1.196248e+06  222.777200      7.055000   443.000000
75%    1.302404e+06  282.942150      7.423750   634.500000
max    1.582770e+06  718.201800      8.183000  2362.000000

In [ ]:
genres_df = movies_df.explode('genre_ids')

genre_counts = genres_df['genre_ids'].value_counts()

genre_counts

genre_ids
53       8
878      7
12       6
28       6
35       6
80       5
27       5
16       3
18       3
10751    3
9648     3
10749    2
14       1
Name: count, dtype: int64

In [ ]:
movies_df.isnull().sum()

id              0
title           0
release_date    0
popularity      0
vote_average    0
vote_count      0
genre_ids       0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')